"""empty message

Revision ID: 38479cc0afcb
Revises: a036887d1ea9
Create Date: 2022-10-15 16:59:40.701163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38479cc0afcb'
down_revision = 'a036887d1ea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
