"""empty message

Revision ID: 4faf66b50475
Revises: c7e4a790424d
Create Date: 2022-10-13 11:11:03.129751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faf66b50475'
down_revision = 'c7e4a790424d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('film_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_type', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_type')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('film_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['film_type_id'], ['film_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films_x_cast_members',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('cast_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], )
    )
    op.create_table('films_x_categories',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['film_categories.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films_x_categories')
    op.drop_table('films_x_cast_members')
    op.drop_table('films')
    op.drop_table('film_types')
    op.drop_table('film_categories')
    # ### end Alembic commands ###
